var ols = {
    "1": [ "U2 R' D' r U2 r' D R / R U' R' U L' U2 R U' R' U2 L", "L' U2 L R U' R' U L' U L / R U R' U' R U R' U R U2 R'", "R U' R' F' R U2 R' U2 R' F R / R U' L' U2 L U2 R' U2 L' U2 L / R U' L' U' L U2 R' U2 L' U L", "U2 L R U' R' U L'", "R U R'", "R U' L' U2 L U L' U L R' / R U R' U R' U2 R U R' U R", "R U R D R' U R D' R' U' R' / R U' R2 D' R U' R' D R2 U' R' / R U' R' U' R2 D R' U' R D' R2", "U L' R U R' U R U' R' U2 L / R U2 R2 D' R U R' D R2 U2 R'", "R U' R D R' U2 R D' R2'", "R U2 R' U R U2 R'", "R U' R' U R' D' R U2 R' D R2 U' R'", "U2 R U' R2 D' R U' R' D R", "R U2 R' U R U' R' U R U' R' U R U2 R'/ R U' R' U' R U R' U' R U R' U' R U' R' / U' L' U R2 U' L U R' U R'", "R U' R' U' R U R' U' R U' R'", "R U' R2 U' R2 U' R2 U2 R", "L' U2 L U L' U L R U2 R'", "R U' R' U' R U' R'", "R U2 R' U' L' U R U' R' L", "R U2 R' U2 R' D' R U2 R' D R2 U' R' / R U' R' L' U R U' R' L U' R U' R'", "U2 L R U' R2 U L' U' R / U2 L R U' R' U2 L' U L U2 L' / U2 R U R' U2 R U R' U2 R U2 R'", "R U2 R' U R U' R' U R U2 R'", "R U R2 U2 R U R' U R", "R U2 R D R' U' R D' R2'", "R U' R' U' R U' R2 U' R U' R' U2 R", "R U R' U R' U' R U' R' U2 R", "U' R U R D R' U R D' R2'", "R U' R' U2 L' U R U' R' L" ],
    "2": [ "L' U2 R U' R' U2 L U R U R' / U' R U2 R D R' U2 R D' R' U' R'", "U' R U R' U R U' R' U' R U' R'", "R' U' R U' R' U2 R2 U R' U R U' R'", "U R U2 R2 U' R U' R' U2 R2 U2 R' / U R' U2 R2 U R2 U R U2 R U' R'", "U2 R' U' R U' R U R2 U R / R U2 R' U2 R U' R' U' R U2 R'", "R L U L' U L U2 L' U' R' / U2 R2 D R' U' R D' R2 U' R U R' / R U2 R U R' U R U2 R' U R'", "U R U R2 D' R U2 R' D R", "U R U' R' U R U2 R' U2 R U R'", "U' R U2 R' U' R2 U R' U R U2 R2 / U R U R' U R U2 R' U R U' R' U' R U' R'", "U R U R' U R U2 R' U R U R'", "R' D' R U R' D R2 U R'", "R U R2 U' R2 U' R2 U2 R2 U R'", "U2 R U2 R' U' R U2 R' U2 R U R'", "U' R U R' U R U R'", "U R U' R' U2 R U R' U' R U R'", "U' R U R' U R U2 R' U R U2 R'", "U2 R U' R' U' R U R'", "U' R U2 R D R' U R D' R2 / U' R U' R2 D' R U R' D R / L U' R' U L' U' R2 U' R'", "R U2 R' L U' R U L' U' R'", "U' L' U2 L U L' U R L U' R'", "U R U R' U' R U R' U2 R U R'", "R U' R' U R U R' U' R U2 R'", "R2 D R' U R D' R' U R'", "R' U2 R U2 R U R' U' R' U R2 U' R' / R U R' U' R U2 R' U R U' R' U2 R U' R'", "U R U R U' L' U R2 U' L / U2 R' U' R U' R U R' U' R' U2 R", "U R' U2 R U R' U R U' R U2 R' / U' L' U2 L U L' U L U R U2 R'", "R U2 R' U2 R U' R' U2 R U' R'" ],
    "3": [ "U' L U' R U2 L' U2 R' U2 L U' L'", "R' U2 R U' R U2 R' U2 R' U' R2 U' R'", "U2 R U2 R' U R U2 R' U R U' R'", "R U R' U2 R U' R' U R U R'U' R U R'", "R U' R' U R U2 R' U R U2 R'", "R' U' R' U' R U R U R2 U R'", "R U2 L' U R' U' L U R U2 R'/R2 D R' U R D' R2'", "R U R' U2 R U R' U2 R U R'", "U2 R U R' U R U' R' U R U R'", "U R' U2 R2 U R U' R' U R2 U' R' U2 R", "R U2 R' U2 R U' R' U R U2 R' U2 R U R'", "U R U2 R' U2 R U R' U2 R U' R'", "R2 U' R' U2 R2 U R' U2 R2 U' R' U2 R", "U R U2 L U' R' U L' R U' R'", "R U' R2 U2 R U R' U R2 U' R'", "R U' R' U R U R'", "R2 U2 R2 U' R2 U' R2 U' R U R'", "R2 U' R' U2 R2 U R' U2 R U R", "U' R2 U R' U R U2 R2", "U' R U R' U R U2 R' U R U' R'", "U' R U' R' U R2 U R' U R U2 R2", "R U' R' U R U' R' U' R U' R'", "U R U2 R' U2 R U R' U' R U2 R'", "R U2 L' U R' U' L R U' R'", "R U2 R' U' R U' R' U' R U R'", "R2 D R' U2 R D' R' U' R'", "U2 L U' R U R' L' U' R U R'" ],
    "4": [ "R U' R' D R D R' U R D' R' D' / U R' U2 R U R' U R2 U2 R' U' R U2 R' / R U2 R' U2 R U2 R' U' R U' R' U R U2 R'", "U' R U R' U R2 U2 R' U' R U' R' U' R' / U' R U' R' U' R' U' R U' R' U2 R2 U R' / R U R' U' R U' R' U R U R' U2 R U R'", "U R U' R' U2 R U2 L U' R' U L' / U R U2 R' U' R U R' U' R U R' U R U' R'", "R' D' R U2 R' D R2 U R' / U2 R U R' U' R U R' U' R U R' U R U' R'", "R' U2 R2 U R' U' R' U2 R", "U' R U2 R' U R' U2 R2 U R2 U R U' / R U R' U2 R U R' U2 R U R' U2 R U' R'", "D R2 U2 R' U R U R2 D' / U' R2 U R2 U R2 U2 R' U R' / R U' R' U2 R U R' U' R U' R' U2 R U2 R'", "R D' R2 U2 R2 U' R2 U' R2 U' D R' / R' U2 R2 U R' L U2 R' U' R U2 L' / R U' R' U R U' R' U' R U' R' U R U2 R'", "R2 U2 R' U' R U' R2 U R U2 R'", "R' U2 R2 U R2 U R", "R2 D R' U2 R D' R' U R' / R U R' U2 R U R' U2 R U R' U' R U2 R'", "U R U' R' U2 R U2 R' U2 R U R'", "U R U' R' L U' R U R' U' R U R' L' / R U' R' U' R U2 R' U' R U R' U R U R'", "R2 U2 R U' R' U R' U2 R' U' R' / R U' R' U2 R U R' U' R U' R' U R U' R'", "R U' R' U R U' R' U2 R U' R'", "R' U2 R2 U R D' R U R' D R2 / U2 R' U2 R U R' U R U' R U R' U2 R U' R' / U2 R U2 R' U R U' R U R' U R U2 R' U' R'", "R2 U2 R' U' R U' R' U' R' / R U' R' U R U' R' U' R U2 R'", "R' U2 R2 U R2 U R2 U2 R' U' R U' R' / U R U R' U2 R U2 R' U2 R U2 R' U' R U2 R'", "U R U R' U2 R2 D R' U2 R D' R' U R' / U' R U R' U R U2 R' U2 R U2 R' U2 R U' R'", "R' D' R U2 R' D R2 U2 R' U R U2 R' / R U R' U2 R U2 R' U R U2 R' U' R U2 R'", "R' U2 R2 U R2 U' R U R' U R / R U R' U R U' R' U' R U R' U R U R'", "U R U' R' U' R U R' U' R U R'", "U2 R U2 R' U' R U R' U' R U R'", "R U2 R' U2 R U2 R' U2 R U' R'", "U2 R' U' R U' R' U2 R2 U R'", "U R U' R' U' R L' U R' U' R L U R' / U' R' U' R U' R' U2 R U' R U2 R' U' R U R'", "R U2 R' U2 R U2 R' U' R U2 R'" ],
    "5": ["U L' U2 R U R' U2 L / U' L' U2 R U' R' U2 L / y' U r D r' U' r D' r' / y2 L F L' U' L U L F' L2 ","U R U' R' ","R' F R U R U' R' F' / U' L U' R U L' U R' ","U R2 D R' U' R D' R2 ","U R U' R' U R' U' R U' R' U2 R / U R U' R' U2 R U2 R' U' R U' R' ","R U' R' U2 R U' R' U2 R U R' ","U R U R' U' R U' R' / R' U' R U R U' R' U' R' U R ","U2 R U' R' U R U2 R' ","U2 F' R U2 R' U2 R' F R / U L' U2 R U L U' L' U R' U2 L ","R' F R2 U R' U' R U R' U' F' / U R U R2 U' R2 U' R2 U2 R / U2 F2 L' U L U L' U' L F2 ","U2 R' U' R2 U' R2 U2 R ","U R U2 L U L' R' U2 L U L' / R' F2 R F2 U L' U L ","U2 R U2 R2 U' R U' R' U2 R / U' F2 L' U L U' L' U' L F2 ","U2 R2 D R' U2 R D' R2 / U2 L' U R U' L U2 R' ","L' U R U' R' L / r' F R F' M' / L' U R U' M' x' ","U2 L' R U R' U' L R U2 R' / U2 M x U R' U' L R U2 R' / U2 R U' R' U' R' F R U R U' R' F' / U R' D' R U R' D R2 U2' R' ","U2 R U2 R' ","R' F' R U2 R U2 R' F / U L' U2 R U' R' U2 L U R U' R' ","R' F2 R2 U' R' U' R U R' F2 / U2 L' U R U' R' L U' R U' R' ","U R U' R' U' R U R' U R U2 R' / U L' U2 L R U R' U L' U L ","U2 R U' R D R' U' R D' R2 / U R U' R2 U2 R U R' U R / U2 R2 D R' U' R D' R' U' R' ","U R U R D R' U2 R D' R2 / U R2 D R' U R D' R' U2 R' ","R2 U R' U R' U' R U R U2 R2 / U2 R' U L U' R2 U L' U R' / U2 R U' R' U L' U R U' R' L U' R U' R' / U2 R U R' U' R U R D R' U R D' R2' ","U2 R U' R' U R U' R' U R U2 R' ","U2 R U2 R2 U2 R U R' U R / U2 R U' R' U R U' R D R' U' R D' R2 ","U R U' R2 U' R U' R' U2 R / U R U R' U F2 L' U L U' L' U' L F2 ","U R U R' U' R U R' U' R U' R' "],
    "6": [ "R L U2 L' U2 R' U2 L U2 L'", "U' R2 U2 R2 U' R2 U' R' U' R' / R D L U2 L' U L U L' D' R'", "R U' R' U' R U2 R' L' U R U' R' L", "D R2 U' R' U' R U2 R2 D'", "U L U' R U' L' U' L U' L' U R'", "R' D' R U2 R' D R U R U' R'", "L U' R U L' U R' U' R U2 R' / U R U R' U R U' R' U' R U2 R'", "R U R' L' U R U' R' U R U' R' L", "R U R' U R' D' R U R' D R2 U' R'", "U R U2 R2 D' R U2 R' D R2 U R'", "U' R U2 R' U' R U' R' U R U2 R'", "R U' R' U' R U2 R' U R U' R'", "L' U L U' R L' U' R' L U2 L' U2 L", "U' R U2 R2 D' R U2 R' D R2 U' R'", "U' R U2 R2 D' R U' R' D R2 U2 R'", "R U' R' U' R U2 R' U2 R U2 R'", "U2 R L U2 R' U2 R U2 R' L' / R' D' R U2 R' D R U2 R U2 R'", "U' R U2 R' L' U2 R U' R' U2 L / U R U R' U R U' R' U2 R U' R'", "U' R U2 R' U' R U2 R'", "R U R' U R U' R' U R U' R'", "R U R' U R U' R' L' U R U' R' L", "U' R U2 R' L U' R U L' U R'", "U2 R U' R' U2 R U R' U' R U2 R'", "U' R U2 R' U L' U R U' R' L", "U2 R2 U' L' U R' U' R' U R U' R' L / R U' R' U2 R U' R' U R U' R' U R U R'", "U' R U2 R' U2 R U' R'", "R U R' U R U' R' U2 R U2 R'" ],
    "7": [ "U' R U R2 D' R U2 R' D R2 U' R'", "U R2 U R U R' U' R' U' R2/ U2 R U R' U2 R U' R' U' R U R'", "L U' R U R' U' R U L' U R' / U' R U R' U2 R2 D R' U' R D' R2", "R' D' R U R' D R U R U' R'", "U' R U R2 D' R U' R' D R2 U2 R' / U2 R U' R U R' U R U2 R' U R'", "R U2 R' U' R U2 R' U' R U R'", "U' R U R' U' R U' R' U R U2 R'", "U L R U' R' U L' R U' R' / U2 F R U R' U' R' F' R2 U' R'", "U' R U R' U L' U R U' R' L / U R U R2 F2 R U2 R U2 R' F2 / U R U' R2 F' R U R U' R' F", "U' R U R' U' F' R U2 R' U2 R' F R / R U' R' U2 R U R' U' R U2 R' U2 R U R'", "U' R U R' U2 R U R' U' R U' R'", "U' R U R' U2 R U' R'", "R U' R' U2 R U2 R' U' R U R'", "L' U' L U R U2 L' U2 R' L / U' R U R' L' U2 R U' R' U2 L", "U2 R U' R' U2 R U' R' U2 R U' R'", "U2 R2 U R2 U R2 U2 R' U' R' / U R2 U2 R2 U' R2 U' R2 U' R U' R' / R U' R' U' R U2 R' U' R U R' U2 R U' R'", "U' R' U' R U' R' U2 R U' R U R'", "U R U R' U R U2 R' U' R U2 R'", "U R2 U2 R2 U' R2 U' R' U2 R' / R U' L U2 L' U' L U' R' L' / R U R U2 R' U' R U' R' U2 R'", "U' R2 U2 R' U' R U' R2 U2 R U' R' / R' U' R U' R' U R U' R' U2 R2 U R' / R U R' U' R U' R' U' R U R' U' R U2 R'", "U' R U R' U2 R U' R2 U' R U' R' U2 R / R U2 R D R' U2 R D' R2 U2 R U' R'", "R' D' R U R' D R U2 R U2 R' / U R U2 R' U2 R2 U R' U R U2 R2 / R U2 R' U2 R U' R' U2 R U2 R' U2 R U2 R'", "U D R2 U R2 U2 R U2 R U' R2 D' / U2 R2 U R2 U R2 U2 R2 U R U2 R' / R U R' U' R U R' U' R U2 R' U' R U R'", "U' L U L' U L U2 R L' U' R' / U R U R' U R U2 R' U2 R U' R'", "U' R2 U2 R' U' R U' R2 U' R U2 R' / R U' R' U2 R U2 R' U' R U' R' U' R U' R'", "U' R U R' U' R U2 R'", "U R U2 R' U' R U' R' U R U R'" ],
    "8": [ "R' D' R U' R' D R U R U' R'", "R U2 R' U R U R' U2 R U2 R'", "U' R2 U R' U R2 U' R' U R' U2 R2", "L U L' U L U R U R' L'", "U2 R U R2 D R' U2 R D' R' U2 R2", "R U' R U2 R2 U' R2 U' R2", "R U2 R' U R U R' U R U' R'", "U R U2 R' D R' U R U2 R' U R D'", "U2 R U R2 D R' U R D' R' U' R2", "U R U2 R2 D R' U R D' R' U' R2", "U R U2 R D R' U' R D' R' U R'", "U2 R U R' U' R U2 R' U R U R'", "R U' R' U R' U' R2 U' R2 U2 R2 U' R'", "U R U2 R2 D R' U2 R D' R' U2 R2", "R U2 R' U2 L' U R U' L U' R'", "U' R2 U2 R U' R' U R' U2 R2", "R L' U' L U' L' U2 L U' R'", "U R' U2 R' U R U' R U2 R2 U' R'", "R U R' U2 R U' R' U2 R U2 R'", "U' R U' R U2 R U' R' U R' U2 R2", "R U R U R' U R U L' U R2 U' L / U2 R U R' U' R U2 R' U R U' R' U' R U' R'", "R U R U' L' U R2 U' L U2 R U R'", "U R U' R' U R2 U R' U R' U' R2 U' R2", "R U R' U2 R U' R' L' U R U' R' L", "R U2 R' U' L U L' U L U2 R U' R' U L'", "R U R' U2 R U' R' U R U' R'", "R U R' U L' U R U' R' L U R U' R'" ],
    "9": [ "R2 U R' U R U2 R' U' R' / R U' R' U R U2 R' U R U R'", "R U R' U R U2 R' U2 R U R'", "U2 R U R' U' R U' R' U2 R U' R'", "L U' R' U L' U' R U' R U R'", "U2 R U2 R' U' R U' R' U R U' R'", "U R U' R' U' R U' R' U R U' R'", "R' U' R U' R' U2 R U' R U' R'", "U2 R2 U2 R' U' R U' R2 / R U' R' U' R U R' U2 R U R'", "R U R' U R U2 L U' R' U L'", "R U' R U' L' U R2 U' L", "U R2 U2 R' U' R U' R' U R'", "U' R U R' U' R2 U2 R' U' R U' R2", "R U' R' U R U2 R' U R U' R' U' R U' R' / U2 R2 U2 R' U2 L' U R U' L R2 /R' U2 R U R' U R2 U R' U2 R U2 R'", "R' U' R U' R' U2 R U' R U R' U' R U' R'", "U' R' U' R U' R' U2 R U R U2 R'", "R U R' U2 R U R' U' R U R'", "U' R U' R' U2 R2 U2 R' U' R U' R' U R'", "R U2 R' U2 R U R' U R U R'", "U L' U' L U' L' R U' R' U2 L", "R2 U R' U R U2 R2 U R U2 R'", "R' U' R U' R' U2 R2 U2 R'", "U2 R' U2 R U R' U R2 U R'", "U' R' U' R U' R' U2 R2 U' R'", "U2 R U' R' U R2 U2 R' U' R U' R2", "U R' U2 R U R' U R2 U R' U R U R'", "R' U' R U' R' U R2 U' R2 U2 R", "U' R U2 R' U' R2 U2 R' U' R U' R2" ],
    "10": [ "R U R' U R U2 R U R' U R U2 R2 / R U R' U R U R' U2 R U' R' U R U R'", "U R U' R2 D' R U R' D R2 U' R' / R U R' U2 R U2 R U R' U R U2 R2 / R U' R' U R U R' U2 R U R' U2 R U R'", "U2 R U R' U' R U2 R' U' R U2 R'", "U R U2 R' U2 R U2 R2 U' R U' R' U2 R", "R U' R' U R2 D R' U R D' R2", "R U2 R' U2 R2 D R' U R D' R2 / R' D R2 U2 R' U2 R U R D' R2", "R' U' R2 U' R2 U2 R U' R U2 R' / U' R2 D R' U' R D' R2 U2 R U R'", "U R U2 R2 F' R U2 R U2 R' F / R U' R' U R L U' R' U R L' U R' / R U' R' U2 R U2 R' U2 R U R' U2 R U' R'", "U R U2 R' U2 R U2 R'", "U2 R U2 R' U R U2 R' L U' R U R' L'", "U' R U' R' U' R U R' U2 R U2 R' / U R U2 R' U R2 D R' U' R D' R2", "R U2 R' U2 R U' R' U R U' R' U' R U' R'", "U R' D R2 U2 R' U2 R U2 R D' R2 / U R U2 R' U2 R2 D R' U2 R D' R2 / U R U' R2 D' R U2 R' D R2 U2 R' / R U' R' U R U2 R' U' R U' R' U' R U R'", "U R U2 R' U2 R U' R' U R U2 R'", "U R U R' U2 R U' R' U2 R U R'", "U' R U' R' U R U' R' U2 R U R'", "R U R' U2 R U' R' U R U2 R' U R U' R'", "R U' R U R' U R U2 R2 / U' R U' R' U' L U' R U R' L' / R U2 R' U2 R U' R' U R U R'", "U R U R' L U' R U R' L' / U R U R' U' R U' R' U2 R U' R' U2 R U2 R'", "U2 R U2 R' U R U' R' U R U' R'", "U R U2 R' U R U' R'", "U' R U R' U R U2 R' U' R U R'", "R U' R' U R U' R' U R U R'", "R U2 R' U R2 U R' U R U2 R2 / R U2 R' U R U' R' U2 R U' R' U R U R'", "U2 R U2 R' U R U' R' U2 R U2 R'", "R' U' R2 U' R2 U2 R U2 R U' R'", "U2 R U R' U' R U2 R' U2 R U' R'" ],
    "11": [ "R U' R' U2 R U R'", "R U L' U2 L U' R' U L' U2 L / U2 R U R' U R2 D R' U' R D' R2 / U' L' U' L U' L' U2 L U R U2 R'", "R U' L U' R' U' L' U' L U' L'", "U2 R U R' L' U2 R U2 R' U2 L", "U' L' U' L U' L' U2 R L U' R'", "R U' L U' R' U L'", "U2 L U' R U R' L'", "R U' R' U2 R L' U R' U' L / R U' R' U2 R U2 R' U R U2 R'", "R' U2 R' U R2 U' R U2 R / U2 R U R' U2 R U' R' U R U2 R'", "U' L U' R U R' L' U R U' R'", "R U R' U' R U2 R U' L' U R2 U' L", "R U L' U2 L U' R' U2 L' U L", "U' L' U' L U' R L' U R' U2 L", "U2 L U' R U L' U2 R' U' R U' R'", "R2 U2 R U' R U R' U2 R2 / R U2 R' U2 R U2 R' U R U R'", "U' R U2 R' U R U2 R' U' R U R'", "R2 U' L' U R' U' L U' R' / U2 R U R' U2 R2 D R' U2 R D' R2 / U2 R U2 R2 D' R U2 R' D R2 U2 R'", "L U L' U L U2 R U' R' U L'", "U' L' U R U' L U' R' / R U2 R2 D' R U' R' D R", "U' R U R' U2 R U2 R' U R U' R'", "U2 R U R' U2 R U2 R'", "U R U R' F' R U R' U R U2 R' F", "R U R' U R U R' U' R U R'", "U2 R U R2 F' R U2 R U2 R' F / U R U' L U L' U2 R' U' L U2 L'", "U' R U R' U2 R U2 R' U2 R U2 R'", "U R U' R' U2 R U' R' U R U' R'", "R U R' U' R U2 R2 D' R U2 R' D R / U R U' R' U2 R U' R' L' U R U' R' L / R U' R' U2 R U R' U' R U2 R' U' R U' R'" ],
    "12": [ "R U2 R' U' R U2 R' U R U2 R'", "R L U2 R' U' R U R' U L' / U2 R2 D R' U R D' R2 U2 R U' R' / U R' U' R U' R' U2 R2 U R' U2 R U' R'/ R U R' U2 R U R' U2 R U R' U R U R' / R U' R' U R U R' U R U2 R' U R U2 R'", "U2 R L U2 L' U' L U' R' L' / U2 R U2 R U2 R' U' R U' R' U2 R' / R U' R' U R U' R' U2 R U R' U2 R U R' / R U R' U' R U' R' U2 R U R' U2 R U2 R'", "U' R U2 R' L' U R U' L U' R' / R U2 R' U' R U R' U' R U R' U R U2 R'", "U R2 D R' U2 R D' R2 U' R U2 R' / U R U' R' U R U' R' U' R U R' U2 R U' R'", "U' R U2 R' U' R U R' U R U' R'", "U R U L U2 L' U' L U' R' L' / U R U' R U2 R' U' R U' R' U2 R' / R U R' U' R U2 R' U2 R U2 R' U R U2 R'", "R U' R' L' U2 L U L' U R L U R' / R2 D R' U R D' R' U2 R' U' R U R' / R U2 R' U' R U2 R' U R U' R' U R U2 R'", "R U R' U' R U2 L U' R' U L' / U R U2 R' U' R U R' U2 R U' R'", "R U' R D R' U' R D' R2 U' R U R' / R U2 R' U' R U R' U2 R U2 R' U' R U' R'", "R U L' U R' U' R L U R' / U' R U' R' U2 R U2 R' U R U' R'", "R' U' R2 U' R U R' U' R U2 R / R U' R' U2 R2 D R' U R D' R' U R' / R U R' U' R U2 R' U2 R U' R' U' R U' R'", "U' R U R' U' L' U R2 U' L U R2 / R U' R2 U' R U' R U R' U' R' U2 R / U R U' R' U2 R U R' U' R U2 R' U' R U R' / U' R U2 R' U' R U R' U R U R' U' R U' R'", "U2 R2 D R' U R D' R2 U' R U2 R' / R U2 R' U2 R U2 R2 D' R U R' D R / U R U R' U' R U2 R' U' R U R' U2 R U' R'", "R U2 R' U' R U R'", "U' R' U2 R2 U R2 U R2 U R' / R U' R' U R U R' U R U' R' U' R U' R'", "U' R U2 R' U' R U R' U2 R U2 R' / U R2 D R' U2 R D' R2 U2 R U' R'", "R U R' U' R U2 R' U2 R U R'", "R U2 R' U R' D' r U2 r' D R / U R U2 R' U2 R U' R' U2 R U' R' U2 R U' R'", "U R' U' R U' R' U2 R2 U R' U' R U2 R' / R U' R' U2 R U' R' U R U R' U' R U2 R'", "R U2 R' U R L U' R' U L' / U2 R U R' U' R U R' U2 R U' R'", "U' R U2 R' U R U' R' U2 R U R'", "R U2 R' U' R U' R' U' R U' R'", "U' R U2 R' U' L U' R U R' L' / R U' R' U' R U R' U' R U R' U2 R U R'", "U' R U' R' U2 R U2 R' U2 R U2 R'", "R2 U2 R' U' R U' R2 U' R U R' / U R U2 R' U' R U R' U' R U2 R'", "U2 R U R' U' R U R' U' R U2 R'" ],
    "13": [ "L' D2 L U2 L' D2 L/U D' R' D R U' R' D' R D", "U' R U' R' U' R U2 R'", "U2 R' D' R2 U2 R' U' R U' R2 D R", "R U R' U' R U' R' U2 R U2 R' / D R' U2 R U' R' U' R", "U' R U' R' U L' U R U' R' L", "U L U' R U L' U' R'/U R U' F U R' U' R F' R'", "R U R' U' R U' R' U R U' R'", "R U' R2 U2 R U R' U R2 U R'", "R U2 R' U R2 U2 R' U' R U' R2", "R2 U R' U R2 U' R2 U R' U2 R2", "R' U R U' R U' R' U2 R U' R2' U' R", "U R' U2 R U R U' R2 U2 R2 U' R'", "R U2 R' U2 R' U' R U' R' U2 R2 U' R'", "U R2 U R' U R U2 R' U R'", "U2 R U' R' U2 R U2 R' U' R U2 R'", "U2 R U R2 U2 R2 U R2 U R / U' R U' R' U2 R U R' U' R U' R'", "R U' R U2 R' U' R U' R2 / R U2 R' U' R U' R' U R U2 R' U R U R'", "U' R U' R2 D' R U2 R' D R2 U' R' / U R U' R' U R U R' U2 R U R' U' R U2 R'", "U' R U' R' U2 R U' R'", "U' R U' R' U' R U' R' U R U2 R'", "U L U' R U R' L' U R U2 R'", "U' R U' R' U2 R2 D R' U' R D' R2", "U2 R U' R' U2 R U2 R' U2 R U' R'", "U R U R' U R U R' U' R U2 R'", "R U R' U' R U' R' L' U R U' R' L / R U' R' U R' U' R U' R' U2 R2 U' R'", "U' R U' R' U' R' U' R2 U' R2 U2 R", "U R U2 R' U' R U R' U R U R'" ],
    "14": [ "L D' L' U L D L'/U R' D' R U' R' D R", "U' L2 D' L' U2 L D L' U2 L' / U' R U R' U' R U' R' U' R U R'", "U R U L U' R' U L' / U R U2 R' U2 R U R' U R U' R'", "L2 D' L' U L D L' U' L' / U R U2 R' U2 R U R' U2 R U2 R'/R' D R' U R D' R' U' R2", "U' R U2 R' U R U R'", "U2 R2 U' L' U R2 U' L / U' R U2 R' U R U2 R' U R U2 R'", "D R' U R U R' U2 R D'", "D R' U R U2 R' U R D'", "R' U R U2 R2 U' R U2 R' U' R2", "U R U R' U2 R U R'", "R U' R' U2 R U' R U2 R2 U' R2 U' R2 / R U2 R' U' R U2 R' U' R U' R' U2 R U R'", "L U2 L' U' L2 D' L' U' L D L2 / U' R U' R' U' R2 U R' U R U2 R2", "U2 R U' R' U2 R U R' U R U R'", "D' L2 U' L U' L' U2 L U' L D / U2 R U' R' U R U' R' U' R U R'", "U' R U L' U R' U' R L U' R' / R U R' U R U R' U2 R U2 R' U2 R U' R'", "U2 R U2 R' U R U2 R' U2 R U R'", "U R U' R' U R U R' U' R U R'", "L2 D' L' U L D L2 U L U2 L' / U2 R U R' U R2 U2 R' U' R U' R' U R' / U R U R' U2 R U R' U' R U2 R' U' R U' R'", "U R' D' R U R' U' R U' R' U2 D R / L D' L' U L D L2 U' L U' L' U2 L", "U2 R U R2 U' R U' R' U2 R2 U2 R' / R U R' U' R U R' U2 R U R' U' R U2 R'", "U R U R' U2 R U2 R' U R U2 R'", "U R U' L' U2 L U' R' U2 L' U L / R U' R' U2 R U R' U2 R U' R' U R U' R'", "U' R U2 R' U' R L U' R' U L'", "L' U2 R U' R' L U L' U R L U' R' / U R U R' U2 R U R2 U2 R U R' U R / R U2 R' U' R U R' U2 R U' R' U R U' R'", "U' R U2 R' U R U' R' U' R U' R'", "U2 R U2 R' U R U2 L U' R' U L' / D' L' U' L U' L' U' L U L' U2 L D", "U' R U2 R2 U2 R U R' U R2 U' R' / R2 D R' U' R D' R' U' R' U' R U' R' / R U2 R' U' R U R' U2 R U' R' U2 R U2 R'" ],
    "15": [ "L' R U R' U' L R U2 R' U' R U R'", "R2 U2 R' U' R U' R' U2 R'", "R U2 R' U2 R U2 R' U' R U R'", "R U R' U' R U2 R' U' R U R'", "U2 R U' R' U' R U R' U' R U2 R'", "U' R2 U2 R' U' R U' R2 U' R U' R'", "R U' R' U2 R U' R' U2 R U' R' U2 R U' R'", "R U2 R' U2 R U R' U' R U2 R' U2 R U R'" ],
    "16": [ "U2 R U' R' U R U2 R' L' U R U' R' L", "R U2 R U R' U R U2 R2", "R U' R' U R U2 R' U2 R U2 R'", "R U' R' U R U2 R' U R U' R'", "R U2 R' U R U' R' U R U R'", "U' R U R' U R2 U R' U R U2 R2", "R U2 R' U2 R U' R' U R U2 R' U2 R U' R'", "R U' R' U2 R U2 R' U R U' R' U2 R U2 R'" ],
    "17": [ "U2 R2 U2' R2' U' R2 U' R2'", "U' R U R' U' L U' R U R' L'/U D' R' D F2 D' R D R' F2 R", "U2 R U' R' U L U' R U R' L'/U R' D' U' R U R' D R U' R' U R", "U2 R L U L U' R' U L' U' L' / U' R U2 R' U2 R U2 R' L' U R U' R' L / U' R U2 R' U2 R U R' L U' R U R' L'", "U2 R U' R' U R U R' U R U' R'", "U' R U R' U' R U R' U R U' R'", "U R U2 R' U' R U2 R' U' R U2 R'", "U2 R U' R' U' R U' R' U2 R U R'", "U R U R' U' R U2 R' U R U' R'", "U' R U R' L' U R U' L U' R'", "L' U2 R2 U2 R2 U' R2 U' R2 L", "R U R' U' R U R' U' R U R'", "R U' R2 U' R U' R' U2 R2 U R'", "U R U R' U' R U2 R' U2 R U2 R'", "U' R U R' U R U' R' U2 R U R'", "R U2 R' U' R U' R' U R U' R' U2 R U' R'", "U' R U2 R' U2 R U2 R' U R U' R'", "y L' U' L U L' U' L U L' U' L", "U2 F' R U R' U R U2 R' F", "U' R U R' U' R U R' U2 R U2 R'", "U R U' R' U R U' R' U R U R' U' R U' R'", "R U R' U2 R U2 R' U2 R U R'", "L' U' L U' L' U' R2 U' L U R2", "R U R' L U' R U R' U' R U R' L'", "R U' R' U2 R2 D R' U2 R D' R' U R'", "U R U2 R' U' R U2 R' U2 R U' R'", "U2 R U2 R' U2 R U' R' U R U' R'" ],
    "18": [ "R' D' R U R' D R2 U' R'", "U R U' R' U2 R L' U2 L U L' U R' L", "U' R U R' U R2 U2 R' U' R U' R2", "U' R' D' R U' R' D R U2 R U' R'", "R U' R' U2 R' U' R2 U' R2 U2 R", "R U' R' U' R U2 R' U' R U2 R'", "U2 R U' R' U2 R U2 R'", "R U' R' U' R U' R' U2 R U' R'", "U R U2 R U2 R' U' R U' R2", "U R U R' U' R U' R' U2 R U R'", "R U' R' U R U' R'", "U R U' R' U R U R' U' R U' R'", "R U R' U R U R' U2 R U2 R'", "R U' R' U' R U' R' U' R U2 R'", "R U2 R' U2 R U' R' U2 R U R'", "R U R' U2 R' U' R2 U' R2 U2 R2 U' R'", "R U2 R U2 R2 U' R2 U' R2", "R U' R' U L U' R U L' U' R'", "U' R U2 R' U' R U2 R' U2 R U2 R'", "U L R U' R' U R U' R' U L'", "U' R2 U R' U R U2 R2 U2 R U R'", "U' R U' R' U2 R U' R' U R U2 R'", "R U' R' L' U R U' R' L", "U' R2 U R' U R U L' U R2 U' L", "R U R' U2 L' U R U' L U' R'", "U R' U' R U' R' U2 R2 U' R' U2 R U2 R'", "R U R' U R U' R' U R2 U2 R' U' R U' R2" ],
    "19": [ "U' F' R U2 R' U2 R' F R2 U R' / R U R' U' R U R' U' R U R' U R U2 R'", "U' R U R2 D' R U' R' D R / F' R U2 R' U' R U R' U2 R' F R", "U R U2 R2 U' R U' R' U2 R2 U R'", "U L' U2 R U2 R' U2 R L U R'", "U R U' R' U2 R2 U2 R2 U' R2 U' R2 / U2 R U R' U2 R U R' U R U R'", "U2 R U2 R' U R U2 R' U R U R' / R2 D R' U R D' R2 U' R U R'", "U' R U2 R' U2 R U R'", "R U R' U' R U2 R' U R U2 R'", "U L' U2 R U2 R' U2 R U R' U' L", "U' R U2 L U' R' U L'", "L' R U R' U' R U R' U' L", "R U R' U R L U' R' U L'", "U' R U' L U' R' U L' U R U R' / R U' R U2 R' U' R U' R2 U' R U R'", "U2 R U' R2 U' R U' R' U2 R2 U2 R'", "U' R U2 R' U2 R L' U R' U' L", "U L' U R U L U L' U L U' R'", "U2 R U2 R2 D' R U2 R' D R", "U L U' R U R' U' R U R' L'", "R U R' U' R U R'", "R U R' U' R U' R' U' R U' R'", "U' R L' U2 L U' R' U2 L' U L / R U R' U' R U' R2 U' R2 U' R2 U2 R", "U' R U2 R' U2 R U' R' U' R U' R'", "R U R' U' R U R' U2 R U2 R' U' R U' R'", "R U2 R' U2 R U' R' U R U R' U' R U2 R'", "U2 R U2 R U' L' U R2 U' L / U R U2 R' U' R U' R' U' R U R' U' R U R'", "L' R U R' U' R L U R'", "R2 U2 R' U' R U' R' U R' U2 R U2 R' / U R U2 R' U2 R2 D R' U2 R D' R' U R' / R U' R' U' R U' R' U2 R U2 R' U2 R U2 R'" ],
    "20": [ "R' U' R' U' R' U R U R", "U R U' R' U R U L U' R' U L' / U2 R U' R2 D' R U2 R' D R2 U R'", "R U' R' U' R2 D R' U R D' R2 /R' F' R U R U' R' F / U' R U R' U' R U R' U' R U' R' U2 R U2 R'", "R2 D' R U' R' U' R U R' D R2 U R / U2 L' U2 R U L U' L' U' R' U2 L / R U' R' U R U2 R' U R U2 R' U R U' R'", "R U R' L' U R U' R' L U R U R'", "U' R U R' L U' R U L' U' R'", "U R U L U' R' U R L' U' R'", "U' R U R' U' R U' R U2 R2 U' R2 U' R2", "U' R U R' U' R U2 R' U' R U2 R' U' R U R'", "U F' U2 L' U L U L' U L F", "U' L U2 L' U2 R U L U' L' U' R'", "U F' R U R' U' R' F R", "R U R' L U' R U R' L' U R U2 R'", "U R2 U R2' U R U' R U' R2'", "R U2 R' U R U2 R' U2 R U' R'", "U R U' R2 U2 R2 U R2 U R", "U' R U' R' U2 R2 U' L' U R2 U' L", "U2 R U' R' U2 R U' R' U' R U R'", "U R' U' R2 U' R2 U2 R2 U R'", "U' R U R' U2 R U2 R' U' R U2 R'", "U2 R2 U R' U R' U' R2 U' R2", "R U2 R' U R U' R' U2 R U' R'", "R U2 R' U R U2 R' U' R U2 R'", "U R U R' U2 R U2 R' U2 R U' R'", "U R U R' U2 R U R' U' R U2 R'", "R U' R' U' R U' R' U R U R'", "R U' R' U' R U R' U R U R'" ]
};


window.algs = {
    //"ZBLL (Jabari Nuruddin, Justin Taylor, Tao Yu)" :zbll_jabari_justin_tao,
   // "ZBLL (Jabari Nuruddin)" :zbll_full,
    //"2UBlocks (Jabari Nuruddin)": d2ublocks,
    //"ZBLL (algdb)" : algdbZBLL,
   // "2GLL": twoGenLL,

   // "Pure OLL (minus dots)": pureoll,
   // "Tripod (akanearcane)": tripod,

    //"VHLS (Chad Batten)": VHLS,
    //"ZBLS (Chad Batten, Tao Yu)": ZBLS ,

    //"OLLCP (Cale Schoon)": ollcp_cale,
   // "OLLCP": algdbOLLCP,
   // "3x3 CLL (Justin Taylor)": cll_333, 
	//"ELL (Justin Taylor & Tao Yu)": ell_justin_tao,
	//"L5EP (Justin, Micki)": L5E,
	//"L5E (Justin Taylor)":l5e_full,
   // "2-Look L5E FR+EO": alg_2lookl5efreo,
  //  "OH CMLL": oh_cmll,
    
   // "ELL": ELL,
   // "F2L": F2L,
    //"PLL": PLL,
    //"OLL (Feliks Zemdegs - Cubeskills)": oll_cubeskills,
   // "OLL": OLL,
    //"COLL": COLL,
    //"COLL (Tao Yu)": taoCOLL,
    //"OH OLL": OHOLL,
   // "OH PLL": OHPLL,
    //"WVLS": WVLS,
    //"VLS (Jayden McNeill)" : vls_jayden_mcneill,
   // "VLS": VLS,
    //"CLS (Justin Taylor)": cls,
    //"ELS (FR) (Justin Taylor)": els_fr,
    //"ELS (BR) (Justin Taylor)": els_br,
	"5-style": ols,
    
  //  "Floating two edge flips (Ishaan Agrawal)": double_edge_flips,
    
    //"CPLS (Arc)": cpls_arc,
   // "CPEOLL" : cpeoll,
	
    
    //"TTLL (Justin Taylor)": ttll,
    //"TSLE": tsle,
    //"TOLS (Justin Taylor)": tols,
    //"Ribbon Multislotting":  ribbon_multislotting,

    //"CMLL": CMLL,
    //"ZBLSE (John McWilliams)": zblse,
    //"42 (Shadowslice)": fortytwo,
   // "Briggs-Taylor Reduction COLL": btrcoll,
    //"OL5C (SqAree)": olfc,
    //"CR (Matt diPalma)" : CR,

    //"CLL": CLL,

    //"EG1": EG1,
   // "EG2": EG2,
    //"Full EG": fullEG,
    //"Ortega OLL": OrtegaOLL,
   // "Ortega PBL": OrtegaPBL,

    //"1LLL (Micki Kanaiya Harning, WIP)" : oneLookLastLayer,
   // "One Look Wednesdays (Daniel Rose-Levine)" : one_look_wednesdays_daniel_roselevine_luigi_soriano,
    //"ZZLL": zzll,
    //"OLLCP (Justin Taylor, WIP)": ollcp ,
    //"EG1 (Finn Ickler)": eg_full,
    //"CP solved OLLCP": cpOLLCP,
    //"F3L": f3l,
    //"test": test,
};
